---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: federation-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: federation-role
subjects:
- kind: ServiceAccount
  name: federation-controller
