apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Basic Install
  name: kubefed-operator.v0.0.8
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Install
      name: installs.operator.kubefed.io
      version: v1alpha1
  description: Prototype first-class operator for Kubernetes federation v2
  displayName: Kubefed Operator
  install:
    spec:
      deployments:
      - name: kubefed-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: kubefed-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: kubefed-operator
            spec:
              containers:
              - command:
                - kubefed-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: kubefed-operator
                image: REPLACE_IMAGE
                imagePullPolicy: Always
                name: kubefed-operator
                resources: {}
              serviceAccountName: kubefed-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - kubefed-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - operator.kubefed.io
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: kubefed-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.0.8
